# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChart, QChartView, QBarSet, QBarSeries, QBarCategoryAxis, QValueAxis, QPieSeries,QPieSlice
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPainter, QColor
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        df = pd.read_csv("Data_startup.csv")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.left_menu_widget.setObjectName("left_menu_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_menu_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.left_menu_widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.left_menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bc_button = QtWidgets.QPushButton(self.frame_4)
        self.bc_button.setObjectName("bc_button")
        self.verticalLayout_3.addWidget(self.bc_button)
        self.pc_button = QtWidgets.QPushButton(self.frame_4)
        self.pc_button.setObjectName("pc_button")
        self.verticalLayout_3.addWidget(self.pc_button)
        self.lc_button = QtWidgets.QPushButton(self.frame_4)
        self.lc_button.setObjectName("lc_button")
        self.verticalLayout_3.addWidget(self.lc_button)
        self.pbc_button = QtWidgets.QPushButton(self.frame_4)
        self.pbc_button.setObjectName("pbc_button")
        self.verticalLayout_3.addWidget(self.pbc_button)
        self.nd_button = QtWidgets.QPushButton(self.frame_4)
        self.nd_button.setObjectName("nd_button")
        self.verticalLayout_3.addWidget(self.nd_button)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.left_menu_widget)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pbc = QtWidgets.QWidget()
        self.pbc.setObjectName("pbc")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pbc)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.pbc)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.pbc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.pbc)
        self.pc = QtWidgets.QWidget()
        self.pc.setObjectName("pc")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pc)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.pc)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.pc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.pc)

        # Get the top 5 categoryKey counts
        category_counts = df['category_list'].value_counts().head(5)

        # Calculate the total count
        total_count = category_counts.sum()

        # Calculate the percentages for each slice
        percentages = category_counts / total_count * 100

        # Create QPieSeries and QPieSlice for each category and percentage
        pie_series = QPieSeries()
        for i, (category, count) in enumerate(category_counts.items()):
            percentage = percentages[category]
            slice = QPieSlice(str(category), percentage)
            pie_series.append(slice)
            slice.setLabel(f"{slice.label()} ({percentage:.1f}%)")

        # Create a QChart object and add the QPieSeries
        chart = QChart()
        chart.addSeries(pie_series)

        # Create a QChartView object and set the displayed chart
        chart_view = QChartView(chart)
        chart_view.setRenderHint(QPainter.Antialiasing)
        self.gridLayout_2.addWidget(chart_view, 0, 0)

        self.nd = QtWidgets.QWidget()
        self.nd.setObjectName("nd")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.nd)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_11 = QtWidgets.QFrame(self.nd)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.nd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_8.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.nd)
        self.lc = QtWidgets.QWidget()
        self.lc.setObjectName("lc")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.lc)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.lc)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.lc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_9.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.lc)
        self.bc = QtWidgets.QWidget()
        self.bc.setObjectName("bc")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.bc)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_15 = QtWidgets.QFrame(self.bc)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_15)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_10.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.bc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_10.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.bc)

        # Filter the DataFrame for status key 1
        df_status_1 = df[df['statusKey'] == 1]
        status_1_counts = df_status_1['fundingKey'].value_counts()

        # Filter the DataFrame for status key 2
        df_status_2 = df[df['statusKey'] == 2]
        status_2_counts = df_status_2['fundingKey'].value_counts()

        # Convert value_counts result for status 1 into a list of values and frequencies
        categories_1 = status_1_counts.index.tolist()
        frequencies_1 = status_1_counts.values.tolist()

        # Convert value_counts result for status 2 into a list of values and frequencies
        categories_2 = status_2_counts.index.tolist()
        frequencies_2 = status_2_counts.values.tolist()

        # Create a QBarSet object for status key 1 and add data from the frequencies list
        barset_1 = QBarSet('success')
        for value in frequencies_1:
            barset_1.append(value)

        # Create a QBarSet object for status key 2 and add data from the frequencies list
        barset_2 = QBarSet('Fail')
        for value in frequencies_2:
            barset_2.append(value)

        # Set different colors for each QBarSet
        barset_1.setColor(QColor(75, 123, 163))  # Blue color for status key 1
        barset_2.setColor(QColor(242, 142, 43))  # Red color for status key 2

        # Create a QBarSeries object and add the QBarSet objects
        barseries = QBarSeries()
        barseries.append(barset_1)
        barseries.append(barset_2)

        # Create a QChart object and add the QBarSeries
        chart = QChart()
        chart.addSeries(barseries)

        # Create a QBarCategoryAxis object and set labels on the x-axis
        axis_x = QBarCategoryAxis()
        for category in categories_1:
            axis_x.append(str(category))
        chart.addAxis(axis_x, Qt.AlignBottom)
        barseries.attachAxis(axis_x)

        # Create a QValueAxis object and set the range and label format on the y-axis
        axis_y = QValueAxis()
        axis_y.setRange(0, max(max(frequencies_1), max(frequencies_2)))  # Set the range based on the maximum value
        axis_y.setLabelFormat("%i")  # Set the label format to integer
        chart.addAxis(axis_y, Qt.AlignLeft)
        barseries.attachAxis(axis_y)

        # Create a QChartView object and set the displayed chart
        chart_view = QChartView(chart)
        chart_view.setRenderHint(QPainter.Antialiasing)
        self.gridLayout_5.addWidget(chart_view, 0, 0)

        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QT CHARTS"))
        self.bc_button.setText(_translate("MainWindow", "Bar Chart"))
        self.pc_button.setText(_translate("MainWindow", "Pai Chart"))
        self.lc_button.setText(_translate("MainWindow", "Line Chart"))
        self.pbc_button.setText(_translate("MainWindow", "Percentage Bar Chart"))
        self.nd_button.setText(_translate("MainWindow", "Nested Donuts"))
        self.label_2.setText(_translate("MainWindow", "Dashboard"))
        self.label_3.setText(_translate("MainWindow", "Percentage Bar Chart"))
        self.label_4.setText(_translate("MainWindow", "Pai Chart"))
        self.label_5.setText(_translate("MainWindow", "Nested Donuts Chart"))
        self.label_6.setText(_translate("MainWindow", "Line Chart"))
        self.label_7.setText(_translate("MainWindow", "Bar Chart"))
